### ISSUE TITLE
Endless loop when selecting to Show Task Manager

### ISSUE THREAD

**Issue by ghost** [madbomb122/Win10Script#1]
Hi, just wanted to drop a quick note. I'm far from an expert powershell guru, but I did run across something that the script was not doing properly.

When selecting the option to show the task manager, it gets stuck in an endless loop while waiting for a value to show up that just won't ever.

Lines 2060 and 2065 (Script version 3.2.8 end with piping the output of the variable assignment to Out-Null. So the variable ends up with a null value.

Removing the pipe to null solves the problem.

Before:
```
$TaskManKey = Get-ItemProperty -Path $Path -Name "Preferences" | Out-Null
If(!($TaskManKey)) {
	$taskmgr = Start-Process -WindowStyle Hidden -FilePath taskmgr.exe -PassThru
	While(!($TaskManKey)) {
		Start-Sleep -m 250
		$TaskManKey = Get-ItemProperty -Path $Path -Name "Preferences" | Out-Null
	}

```
After:
```
$TaskManKey = Get-ItemProperty -Path $Path -Name "Preferences"
If(!($TaskManKey)) {
	$taskmgr = Start-Process -WindowStyle Hidden -FilePath taskmgr.exe -PassThru
	While(!($TaskManKey)) {
		Start-Sleep -m 250
		$TaskManKey = Get-ItemProperty -Path $Path -Name "Preferences"
	}
```

Like I said, I'm still at an intermediate level with Powershell, so if my thoughts are wrong, please let me know.  Otherwise, I hope I helped.

-- David

**Comment by madbomb122** [comment]
thanks for posting this issue, and you are not wrong with that happens with this.

Issue fixed in v3.2.9
