### ISSUE TITLE
Feature Request: Enable / Disable Activity Feed (timeline)

### ISSUE THREAD

**Issue by ghost** [madbomb122/Win10Script#4]
With the last spring update, Windows add a new feature called Timeline.  

It is possible to add enable/disable this feature from Win10Script?  

Following [this link by Microsoft](https://docs.microsoft.com/en-us/windows/client-management/mdm/policy-csp-privacy#privacy-enableactivityfeed), it can be done by the key register 
`EnableActivityFeed` in `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System`.

Thanks :)

**Comment by madbomb122** [comment]
I have added the request and it has now been released
