### ISSUE TITLE
Infinite loop 'Disabling Share/Share with'

### ISSUE THREAD

**Issue by Capt0rr** [madbomb122/Win10Script#5]
Tested: `v.3.5.0`

Offending line:
```
Set-ItemProperty -LiteralPath 'HKCR:\*\shellex\ContextMenuHandlers\Sharing' -Name '(Default)' -Type String -Value ''
```

but the last one works fine:
```
Set-ItemProperty -Path 'HKCR:\*\shellex\ContextMenuHandlers\ModernSharing' -Name '(Default)' -Type String -Value ''
```

Windows 10 Pro 1803 

Thanks for your awesome work!

**Comment by madbomb122** [comment]
Thanks for letting me know, however I just did a test, and it was the other way around for me.. 
without the `-LiteralPath` , the function looks at the wildcard `*` and does more paths than it should

The issue has been fixed and posted. (c3.5.1)
I also gave a thanks to you in the changelog

**Comment by Capt0rr** [comment]
Yep confirmed fixed and confirmed I wrote it backwards.
