### ISSUE TITLE
Cortana registry HKCU changing i believe is wrong

### ISSUE THREAD

**Issue by renato-ll** [madbomb122/Win10Script#7]
Is there something wrong with this part of the script?

The toggles between Cortana enabling or disabling are change some another registries(Ink & Pen) but not affecting Cortana

	If($Cortana -eq 0) {
		If($ShowSkipped -eq 1){ DisplayOut 'Skipping Cortana...' -C 15 }
	} ElseIf($Cortana -eq 1) {
		DisplayOut 'Enabling Cortana...' -C 11
		$Path = 'HKCU:\SOFTWARE\Microsoft\InputPersonalization'
		Remove-ItemProperty -Path 'HKCU:\SOFTWARE\Microsoft\Personalization\Settings' -Name 'AcceptedPrivacyPolicy'
		Remove-ItemProperty -Path "$Path\TrainedDataStore" -Name 'HarvestContacts'
		Set-ItemProperty -Path $Path -Name 'RestrictImplicitTextCollection' -Type DWord -Value 0
		Set-ItemProperty -Path $Path -Name 'RestrictImplicitInkCollection' -Type DWord -Value 0
	} ElseIf($Cortana -eq 2) {
		DisplayOut 'Disabling Cortana...' -C 12
		$Path = CheckSetPath 'HKCU:\SOFTWARE\Microsoft\Personalization\Settings'
		Set-ItemProperty -Path $Path -Name 'AcceptedPrivacyPolicy' -Type DWord -Value 0
		$Path = CheckSetPath 'HKCU:\SOFTWARE\Microsoft\InputPersonalization'
		Set-ItemProperty -Path $Path -Name 'RestrictImplicitTextCollection' -Type DWord -Value 1
		Set-ItemProperty -Path $Path -Name 'RestrictImplicitInkCollection' -Type DWord -Value 1
		$Path = CheckSetPath "$Path\TrainedDataStore"
		Set-ItemProperty -Path $Path -Name 'HarvestContacts' -Type DWord -Value 0
	}

I've found some Cortana HKCU registries that the script doesnt change:
 "CortanaEnabled"
"CanCortanaBeEnabled" 
"DeviceHistoryEnabled" 
"CortanaConsent" 
"CortanaInAmbientMode"
"BingSearchEnabled" 
"VoiceActivationEnableAboveLockscreen" 
"HistoryViewEnabled"

**Comment by madbomb122** [comment]
may i ask what version of windows are you using?

**Comment by renato-ll** [comment]
Windows 10 1803 64 bits

**Comment by madbomb122** [comment]
thanks for letting me know, i'll take a look at it when i can

**Comment by renato-ll** [comment]
Ok thanks 

Im not telling Cortana aren't being disabled after the script ran, but i was just looking the script to use later on my Notebook
And i believe it isnt from Cortana HKCU registries:
"RestrictImplicitTextCollection"
"HarvestContacts"
"RestrictImplicitTextCollection" 

But i may be wrong

**Comment by madbomb122** [comment]
the settings in the script does disable some Cortana items but it's mostly privacy stuff.

i will take a look at the settings you listed and see what they do.

**Comment by madbomb122** [comment]
i looked at the items you listed.. seems like most of those were to fix cortana issues for people that upgraded to the Anniversary Update.

but i did add some items to the cortana disable
