### ISSUE TITLE
Telemetry Issue

### ISSUE THREAD

**Issue by ghost** [madbomb122/Win10Script#9]
Disabling Telemetry = Enabling
Enabling Telemetry = Disabling

https://github.com/madbomb122/Win10Script/blob/f368023241abd613fe94cb1d6215e18f52a3f7d5/Win10-Menu.ps1#L1683

**Comment by madbomb122** [comment]
thanks for letting me know..
i'll fix it in the next update (should be soon) with alot of updates

**Comment by madbomb122** [comment]
This should now be fixed in v3.7.1
